Config:
  #Do not change the ConfigVersion. This will cause a reset of the config.yml
  ConfigVersion: "1.0.0"

  Blocks:
    #this one is the block to identify the trashcan
    top: "IRON_TRAPDOOR"
    #The block "low" has to be a block with an inventory e.g. Chest, Hopper, Dropper...
    low: "DROPPER"